### ISSUE TITLE
A simple landing page for the system

### ISSUE THREAD

**Issue by xlarsx** [iTermin/server#14]

**Comment by EstefaniaGuardado** [comment]
Hi @xlarsx when I start the server (npm start), doesn't work

![screen shot 2016-04-22 at 11 12 03](https://cloud.githubusercontent.com/assets/7373862/14737217/3f9452dc-087b-11e6-8f90-733da45a4384.png)

**Comment by xlarsx** [comment]
You have to install first the dependencies:

``` bash
npm install
```

**Comment by estefaniaguardado** [comment]
@xlarsx it's working, thank you

**Comment by xlarsx** [comment]
Great! Enjoy coding!
