### ISSUE TITLE
Date error

### ISSUE THREAD

**Issue by xlarsx** [iTermin/server#23]
![](http://i.imgur.com/8NnMvcX.jpg)

http://blueberry-crumble-60073.herokuapp.com/meetingDetail/F2432B1C-4DF0-42CE-806F-2401E9B5FF3E

**Comment by EstefaniaGuardado** [comment]
In web, the error isn't showing

**Comment by estefaniaguardado** [comment]
![img_0811](https://cloud.githubusercontent.com/assets/7373862/14423138/78c8a994-ffda-11e5-827d-c19d1fea11ce.PNG)

![screen shot 2016-04-11 at 11 08 16](https://cloud.githubusercontent.com/assets/7373862/14423023/f140252e-ffd9-11e5-9d85-11556f2935ec.png)

Don't show error in web-mobile and web-desktop

**Comment by estefaniaguardado** [comment]
[fiery-fire-7264-export (1).txt](https://github.com/iTermin/server/files/220460/fiery-fire-7264-export.1.txt)
