### ISSUE TITLE
Don't show page of the meeting detail

### ISSUE THREAD

**Issue by estefaniaguardado** [iTermin/server#24]
![](http://i.imgur.com/VBc2bIB.jpg)

**Comment by EstefaniaGuardado** [comment]
``

**Comment by estefaniaguardado** [comment]
[fiery-fire-7264-export (1).txt](https://github.com/xlarsx/servermeetingapp/files/211781/fiery-fire-7264-export.1.txt)

**Comment by estefaniaguardado** [comment]
![](http://i.imgur.com/5qsB3Yr.jpg)

Error in database in array of guests because first position (0) has been deleted, fix mistake adding correctly the information of guests in array.
